import type { L } from '../types';

/** Stress-drill word bank for the Practice page.
 *  Row format: [syllables joined with "-", index of the stressed syllable, en, de, ru].
 *  Syllabification conventions: see stressRule.ts. `npm run check` recomputes every stress
 *  from the syllables + macrons, so a wrong macron or index fails the build.
 *  Session 1's own stress words are deliberately not repeated here. */
type Row = [string, number, string, string, string];

const ROWS: Row[] = [
  // ---- two syllables: always the first ----
  ['Rō-ma', 0, 'Rome', 'Rom', 'Рим'],
  ['pa-ter', 0, 'father', 'Vater', 'отец'],
  ['mā-ter', 0, 'mother', 'Mutter', 'мать'],
  ['frā-ter', 0, 'brother', 'Bruder', 'брат'],
  ['so-ror', 0, 'sister', 'Schwester', 'сестра'],
  ['a-qua', 0, 'water', 'Wasser', 'вода'],
  ['ter-ra', 0, 'earth, land', 'Erde, Land', 'земля'],
  ['vī-ta', 0, 'life', 'Leben', 'жизнь'],
  ['lin-gua', 0, 'tongue, language', 'Zunge, Sprache', 'язык'],
  ['au-rum', 0, 'gold', 'Gold', 'золото'],
  ['mun-dus', 0, 'world', 'Welt', 'мир'],
  ['ver-bum', 0, 'word', 'Wort', 'слово'],
  ['vī-num', 0, 'wine', 'Wein', 'вино'],
  ['pā-nis', 0, 'bread', 'Brot', 'хлеб'],
  ['lū-na', 0, 'moon', 'Mond', 'луна'],
  ['stel-la', 0, 'star', 'Stern', 'звезда'],
  ['sil-va', 0, 'forest', 'Wald', 'лес'],
  ['pu-er', 0, 'boy', 'Junge', 'мальчик'],
  ['por-ta', 0, 'gate', 'Tor', 'ворота'],
  ['cae-lum', 0, 'sky, heaven', 'Himmel', 'небо'],
  ['ho-mō', 0, 'human being', 'Mensch', 'человек'],
  ['a-mor', 0, 'love', 'Liebe', 'любовь'],
  ['do-mus', 0, 'house, home', 'Haus', 'дом'],
  ['cor-pus', 0, 'body', 'Körper', 'тело'],
  ['tem-pus', 0, 'time', 'Zeit', 'время'],
  ['ca-put', 0, 'head', 'Kopf', 'голова'],
  ['no-men', 0, 'name', 'Name', 'имя'],
  ['lū-men', 0, 'light', 'Licht', 'свет'],
  ['fā-ma', 0, 'fame, rumour', 'Ruhm, Gerücht', 'молва, слава'],
  ['cau-sa', 0, 'cause, case', 'Ursache, Fall', 'причина, дело'],
  ['cū-ra', 0, 'care', 'Sorge', 'забота'],
  ['De-us', 0, 'God', 'Gott', 'Бог'],
  ['fi-dēs', 0, 'faith, trust', 'Glaube, Treue', 'вера, верность'],
  ['ag-nus', 0, 'lamb', 'Lamm', 'ягнёнок'],
  ['ig-nis', 0, 'fire', 'Feuer', 'огонь'],
  ['vī-dī', 0, 'I saw', 'ich sah', 'я увидел'],
  ['vī-cī', 0, 'I conquered', 'ich siegte', 'я победил'],
  ['mag-nus', 0, 'great, big', 'groß', 'большой, великий'],
  ['bo-nus', 0, 'good', 'gut', 'хороший'],
  ['to-ga', 0, 'toga', 'Toga', 'тога'],
  ['nau-ta', 0, 'sailor', 'Seemann', 'моряк'],
  ['Chris-tus', 0, 'Christ', 'Christus', 'Христос'],
  ['sanc-tus', 0, 'holy', 'heilig', 'святой'],
  ['tem-plum', 0, 'temple', 'Tempel', 'храм'],
  ['fo-rum', 0, 'forum, market square', 'Forum, Marktplatz', 'форум, площадь'],
  ['Mā-ius', 0, 'May', 'Mai', 'май'],
  ['Iū-nō', 0, 'Juno', 'Juno', 'Юнона'],
  ['Ve-nus', 0, 'Venus', 'Venus', 'Венера'],
  ['vir-tūs', 0, 'courage, virtue', 'Tapferkeit, Tugend', 'доблесть'],
  ['la-bor', 0, 'work, toil', 'Arbeit, Mühe', 'труд'],
  ['a-mō', 0, 'I love', 'ich liebe', 'я люблю'],
  ['sa-cer', 0, 'sacred', 'heilig', 'священный'],

  // ---- long penult: long vowel (macron) ----
  ['na-tū-ra', 1, 'nature', 'Natur', 'природа'],
  ['fi-gū-ra', 1, 'shape, figure', 'Gestalt, Figur', 'фигура, облик'],
  ['cul-tū-ra', 1, 'cultivation', 'Anbau, Pflege', 'возделывание'],
  ['fu-tū-rus', 1, 'future, about to be', 'künftig', 'будущий'],
  ['ma-tū-rus', 1, 'ripe', 'reif', 'спелый, зрелый'],
  ['sē-cū-rus', 1, 'carefree, safe', 'sorglos, sicher', 'беззаботный'],
  ['ob-scū-rus', 1, 'dark', 'dunkel', 'тёмный'],
  ['re-gī-na', 1, 'queen', 'Königin', 'царица'],
  ['ru-ī-na', 1, 'collapse, ruin', 'Einsturz, Ruine', 'обвал, руина'],
  ['doc-trī-na', 1, 'teaching', 'Lehre', 'учение'],
  ['me-di-cī-na', 2, 'medicine', 'Medizin', 'медицина'],
  ['dis-ci-plī-na', 2, 'training, discipline', 'Unterricht, Zucht', 'обучение, дисциплина'],
  ['ve-nē-num', 1, 'poison', 'Gift', 'яд'],
  ['se-rē-nus', 1, 'clear, calm', 'heiter, klar', 'ясный, безмятежный'],
  ['ha-rē-na', 1, 'sand, arena', 'Sand, Arena', 'песок, арена'],
  ['Rō-mā-nus', 1, 'Roman', 'römisch', 'римский'],
  ['La-tī-nus', 1, 'Latin', 'lateinisch', 'латинский'],
  ['Ger-mā-nus', 1, 'Germanic', 'germanisch', 'германский'],
  ['A-thē-nae', 1, 'Athens', 'Athen', 'Афины'],
  ['Car-thā-gō', 1, 'Carthage', 'Karthago', 'Карфаген'],
  ['Eu-rō-pa', 1, 'Europe', 'Europa', 'Европа'],
  ['A-prī-lis', 1, 'April', 'April', 'апрель'],
  ['Oc-tō-ber', 1, 'October', 'Oktober', 'октябрь'],
  ['Nep-tū-nus', 1, 'Neptune', 'Neptun', 'Нептун'],
  ['Vul-cā-nus', 1, 'Vulcan', 'Vulcanus', 'Вулкан'],
  ['Cu-pī-dō', 1, 'Cupid; desire', 'Cupido; Begierde', 'Купидон; желание'],
  ['Di-ā-na', 1, 'Diana', 'Diana', 'Диана'],
  ['Ae-nē-ās', 1, 'Aeneas', 'Äneas', 'Эней'],
  ['Pa-lā-tī-num', 2, 'the Palatine hill', 'der Palatin', 'Палатин'],
  ['Co-los-sē-um', 2, 'the Colosseum', 'das Kolosseum', 'Колизей'],
  ['pa-ra-dī-sus', 2, 'paradise', 'Paradies', 'рай'],
  ['an-tī-quus', 1, 'old, ancient', 'alt, antik', 'древний'],
  ['be-ā-tus', 1, 'blessed, happy', 'selig, glücklich', 'блаженный'],
  ['po-ē-ta', 1, 'poet', 'Dichter', 'поэт'],
  ['ath-lē-ta', 1, 'athlete', 'Athlet', 'атлет'],
  ['pro-phē-ta', 1, 'prophet', 'Prophet', 'пророк'],
  ['pla-nē-ta', 1, 'planet', 'Planet', 'планета'],
  ['co-mē-ta', 1, 'comet', 'Komet', 'комета'],
  ['ca-dū-cus', 1, 'falling, perishable', 'hinfällig, vergänglich', 'падающий, бренный'],
  ['mi-nū-tus', 1, 'small, minute', 'winzig', 'мелкий'],
  ['fi-dē-lēs', 1, 'faithful (pl.)', 'treu, Gläubige', 'верные'],

  // infinitives: -āre / -ēre / -īre are stressed, 3rd-conjugation -ere is not
  ['a-mā-re', 1, 'to love', 'lieben', 'любить'],
  ['lau-dā-re', 1, 'to praise', 'loben', 'хвалить'],
  ['por-tā-re', 1, 'to carry', 'tragen', 'нести'],
  ['vo-cā-re', 1, 'to call', 'rufen', 'звать'],
  ['ne-gā-re', 1, 'to deny', 'verneinen', 'отрицать'],
  ['cre-ā-re', 1, 'to create', 'erschaffen', 'творить'],
  ['ō-rā-re', 1, 'to pray, to speak', 'beten, reden', 'молиться, говорить'],
  ['la-bō-rā-re', 2, 'to work', 'arbeiten', 'трудиться'],
  ['ha-bē-re', 1, 'to have', 'haben', 'иметь'],
  ['mo-nē-re', 1, 'to warn, remind', 'mahnen', 'предостерегать'],
  ['vi-dē-re', 1, 'to see', 'sehen', 'видеть'],
  ['te-nē-re', 1, 'to hold', 'halten', 'держать'],
  ['ta-cē-re', 1, 'to be silent', 'schweigen', 'молчать'],
  ['au-dī-re', 1, 'to hear', 'hören', 'слышать'],
  ['ve-nī-re', 1, 'to come', 'kommen', 'приходить'],
  ['dor-mī-re', 1, 'to sleep', 'schlafen', 'спать'],
  ['fī-nī-re', 1, 'to finish, limit', 'beenden, begrenzen', 'заканчивать, ограничивать'],
  ['ser-vī-re', 1, 'to serve', 'dienen', 'служить'],
  ['le-ge-re', 0, 'to read', 'lesen', 'читать'],
  ['re-ge-re', 0, 'to rule', 'regieren', 'править'],
  ['dī-ce-re', 0, 'to say', 'sagen', 'говорить'],
  ['dū-ce-re', 0, 'to lead', 'führen', 'вести'],
  ['vī-ve-re', 0, 'to live', 'leben', 'жить'],
  ['scrī-be-re', 0, 'to write', 'schreiben', 'писать'],
  ['cur-re-re', 0, 'to run', 'laufen', 'бежать'],
  ['mit-te-re', 0, 'to send', 'schicken', 'посылать'],
  ['pō-ne-re', 0, 'to put', 'setzen, legen', 'класть, ставить'],
  ['ca-pe-re', 0, 'to take', 'nehmen', 'брать'],
  ['fa-ce-re', 0, 'to do, make', 'machen, tun', 'делать'],
  ['crē-de-re', 0, 'to believe', 'glauben', 'верить'],
  ['lū-de-re', 0, 'to play', 'spielen', 'играть'],
  ['bi-be-re', 0, 'to drink', 'trinken', 'пить'],
  ['cog-nō-sce-re', 1, 'to get to know', 'kennenlernen', 'узнавать'],

  // verb forms: -āmus / -ēmus / -īmus stressed, 3rd-conjugation -imus not
  ['a-mā-mus', 1, 'we love', 'wir lieben', 'мы любим'],
  ['a-mā-tis', 1, 'you (pl.) love', 'ihr liebt', 'вы любите'],
  ['ha-bē-mus', 1, 'we have', 'wir haben', 'мы имеем'],
  ['vi-dē-mus', 1, 'we see', 'wir sehen', 'мы видим'],
  ['au-dī-mus', 1, 'we hear', 'wir hören', 'мы слышим'],
  ['le-gi-mus', 0, 'we read', 'wir lesen', 'мы читаем'],
  ['dī-ci-mus', 0, 'we say', 'wir sagen', 'мы говорим'],
  ['crē-di-mus', 0, 'we believe', 'wir glauben', 'мы верим'],
  ['vī-vi-mus', 0, 'we live', 'wir leben', 'мы живём'],
  ['a-mā-vit', 1, 'he/she loved', 'er/sie liebte', 'он(а) любил(а)'],
  ['a-mā-vi-mus', 1, 'we loved', 'wir liebten', 'мы любили'],
  ['ve-nī-te', 1, 'come! (pl.)', 'kommt!', 'придите!'],
  ['ō-rā-te', 1, 'pray! (pl.)', 'betet!', 'молитесь!'],
  ['lau-dā-te', 1, 'praise! (pl.)', 'lobt!', 'хвалите!'],
  ['ad-es-te', 1, 'be present! come!', 'seid da! kommt!', 'приидите!'],
  ['mi-se-rē-re', 2, 'have mercy!', 'erbarme dich!', 'помилуй!'],

  // suffix -ālis (ā always long)
  ['ae-quā-lis', 1, 'equal', 'gleich', 'равный'],
  ['nā-tū-rā-lis', 2, 'natural', 'natürlich', 'естественный'],
  ['so-ci-ā-lis', 2, 'companionable, social', 'gesellig, sozial', 'общественный'],
  ['lē-gā-lis', 1, 'legal', 'gesetzlich', 'законный'],
  ['rē-gā-lis', 1, 'royal', 'königlich', 'царский'],
  ['mor-tā-lis', 1, 'mortal', 'sterblich', 'смертный'],
  ['vī-tā-lis', 1, 'of life, vital', 'Lebens-, vital', 'жизненный'],
  ['ca-pi-tā-lis', 2, 'of the head, capital', 'Haupt-, kapital', 'головной, главный'],
  ['fī-nā-lis', 1, 'of the end, final', 'End-, final', 'конечный'],
  ['a-ni-mā-lis', 2, 'living, animal', 'lebendig, tierisch', 'живой, животный'],
  ['hos-pi-tā-lis', 2, 'hospitable', 'gastfreundlich', 'гостеприимный'],
  // suffix -ārius / -ārium (stressed ā because ri before a vowel is short)
  ['sa-lā-ri-um', 1, 'salt money, salary', 'Salzgeld, Gehalt', '«соляные» деньги, жалованье'],
  ['ae-rā-ri-um', 1, 'treasury', 'Staatskasse', 'казна'],
  ['a-quā-ri-us', 1, 'water-carrier; Aquarius', 'Wasserträger; Wassermann', 'водонос; Водолей'],
  ['lī-brā-ri-us', 1, 'scribe, bookseller', 'Schreiber, Buchhändler', 'писец, книготорговец'],
  ['ad-ver-sā-ri-us', 2, 'opponent', 'Gegner', 'противник'],
  ['vo-ca-bu-lā-ri-um', 3, 'vocabulary', 'Wortschatz', 'словарь'],
  ['Iā-nu-ā-ri-us', 2, 'January', 'Januar', 'январь'],
  ['Fe-bru-ā-ri-us', 2, 'February', 'Februar', 'февраль'],
  // suffix -ātus / -ātor
  ['se-nā-tus', 1, 'senate', 'Senat', 'сенат'],
  ['ma-gis-trā-tus', 2, 'office, magistrate', 'Amt, Beamter', 'должность, магистрат'],
  ['dic-tā-tor', 1, 'dictator', 'Diktator', 'диктатор'],
  ['ō-rā-tor', 1, 'speaker', 'Redner', 'оратор'],
  ['se-nā-tor', 1, 'senator', 'Senator', 'сенатор'],
  ['gla-di-ā-tor', 2, 'gladiator', 'Gladiator', 'гладиатор'],
  ['cre-ā-tor', 1, 'creator', 'Schöpfer', 'творец'],
  ['vi-ā-tor', 1, 'traveller', 'Reisender', 'путник'],
  ['im-pe-rā-tor', 2, 'commander, emperor', 'Feldherr, Kaiser', 'полководец, император'],
  ['ō-rā-tō-ris', 2, 'of the speaker', 'des Redners', 'оратора (род. п.)'],
  // suffix -ōsus
  ['glō-ri-ō-sus', 2, 'glorious, boastful', 'ruhmreich, prahlerisch', 'славный, хвастливый'],
  ['cū-ri-ō-sus', 2, 'careful, curious', 'sorgfältig, neugierig', 'тщательный, любопытный'],
  ['fā-mō-sus', 1, 'famous, notorious', 'berühmt, berüchtigt', 'известный, пресловутый'],
  ['for-mō-sus', 1, 'beautiful', 'schön', 'прекрасный'],
  ['pe-rī-cu-lō-sus', 3, 'dangerous', 'gefährlich', 'опасный'],
  ['nu-me-rō-sus', 2, 'numerous', 'zahlreich', 'многочисленный'],
  ['ge-ne-rō-sus', 2, 'noble, generous', 'edel, großzügig', 'благородный, щедрый'],
  ['o-di-ō-sus', 2, 'hateful', 'verhasst', 'ненавистный'],
  ['vi-ti-ō-sus', 2, 'faulty, vicious', 'fehlerhaft, lasterhaft', 'порочный'],
  // -tiō vs -tiōnis: the stress moves when a syllable is added
  ['nā-ti-ō', 0, 'birth, nation', 'Geburt, Volk', 'рождение, народ'],
  ['nā-ti-ō-nis', 2, 'of the nation', 'des Volkes', 'народа (род. п.)'],
  ['ra-ti-ō', 0, 'reason, calculation', 'Vernunft, Berechnung', 'разум, расчёт'],
  ['ra-ti-ō-nis', 2, 'of reason', 'der Vernunft', 'разума (род. п.)'],
  ['lec-ti-ō', 0, 'reading', 'Lesung', 'чтение'],
  ['lec-ti-ō-nis', 2, 'of the reading', 'der Lesung', 'чтения (род. п.)'],
  ['quaes-ti-ō', 0, 'question, inquiry', 'Frage, Untersuchung', 'вопрос, расследование'],
  ['ō-rā-ti-ō', 1, 'speech', 'Rede', 'речь'],
  ['re-li-gi-ō', 1, 'religion, scruple', 'Religion, Gewissenhaftigkeit', 'религия, благочестие'],
  ['con-di-ci-ō', 1, 'condition, terms', 'Bedingung', 'условие'],
  // -tās vs -tātis
  ['lī-ber-tās', 1, 'freedom', 'Freiheit', 'свобода'],
  ['lī-ber-tā-tis', 2, 'of freedom', 'der Freiheit', 'свободы (род. п.)'],
  ['ve-ri-tā-tis', 2, 'of truth', 'der Wahrheit', 'истины (род. п.)'],
  ['cī-vi-tās', 0, 'citizenship, state', 'Bürgerschaft, Staat', 'гражданство, государство'],
  ['ū-ni-ver-si-tās', 2, 'the whole, corporation', 'Gesamtheit, Körperschaft', 'совокупность, корпорация'],
  ['so-ci-e-tās', 1, 'partnership, society', 'Gemeinschaft, Gesellschaft', 'союз, общество'],
  ['cā-ri-tās', 0, 'love, dearness', 'Liebe, Wertschätzung', 'любовь, дороговизна'],
  ['vo-lun-tās', 1, 'will', 'Wille', 'воля'],
  ['gra-vi-tās', 0, 'weight, dignity', 'Gewicht, Würde', 'тяжесть, достоинство'],
  ['hū-mā-ni-tās', 1, 'humanity, culture', 'Menschlichkeit, Bildung', 'человечность, образованность'],
  ['fē-lī-ci-tās', 1, 'happiness, luck', 'Glück', 'счастье'],
  // other stem changes
  ['a-mō-ris', 1, 'of love', 'der Liebe', 'любви (род. п.)'],
  ['la-bō-ris', 1, 'of work', 'der Arbeit', 'труда (род. п.)'],
  ['vir-tū-tis', 1, 'of courage', 'der Tapferkeit', 'доблести (род. п.)'],
  ['ho-mi-nis', 0, 'of the human being', 'des Menschen', 'человека (род. п.)'],
  ['cor-po-ris', 0, 'of the body', 'des Körpers', 'тела (род. п.)'],
  ['tem-po-ris', 0, 'of time', 'der Zeit', 'времени (род. п.)'],
  ['no-mi-nis', 0, 'of the name', 'des Namens', 'имени (род. п.)'],
  ['ca-pi-tis', 0, 'of the head', 'des Kopfes', 'головы (род. п.)'],
  ['o-pe-ra', 0, 'works (pl.)', 'Werke', 'труды, произведения'],

  // ---- long penult: diphthong ----
  ['a-moe-nus', 1, 'pleasant, lovely', 'lieblich', 'приятный, прелестный'],
  ['Cen-tau-rus', 1, 'centaur', 'Kentaur', 'кентавр'],
  ['thē-sau-rus', 1, 'treasure, treasury', 'Schatz', 'сокровище'],
  ['Mī-nō-tau-rus', 2, 'the Minotaur', 'der Minotaurus', 'Минотавр'],
  ['dī-nō-sau-rus', 2, 'dinosaur (modern)', 'Dinosaurier (neulat.)', 'динозавр (новолат.)'],

  // ---- long penult: closed syllable (two consonants follow) ----
  ['Mi-ner-va', 1, 'Minerva', 'Minerva', 'Минерва'],
  ['Au-gus-tus', 1, 'Augustus; August', 'Augustus; August', 'Август; август'],
  ['Ae-gyp-tus', 1, 'Egypt', 'Ägypten', 'Египет'],
  ['Sep-tem-ber', 1, 'September', 'September', 'сентябрь'],
  ['No-vem-ber', 1, 'November', 'November', 'ноябрь'],
  ['De-cem-ber', 1, 'December', 'Dezember', 'декабрь'],
  ['A-pol-lō', 1, 'Apollo', 'Apollo', 'Аполлон'],
  ['Sā-tur-nus', 1, 'Saturn', 'Saturn', 'Сатурн'],
  ['A-chil-lēs', 1, 'Achilles', 'Achilles', 'Ахилл'],
  ['mo-der-nus', 1, 'modern (medieval word)', 'modern (mittellat.)', 'современный (средневек.)'],
  ['ae-ter-nus', 1, 'eternal', 'ewig', 'вечный'],
  ['su-per-bus', 1, 'proud', 'stolz, hochmütig', 'гордый, надменный'],
  ['ho-nes-tus', 1, 'honourable', 'ehrenhaft', 'честный, почтенный'],
  ['mo-des-tus', 1, 'modest', 'bescheiden', 'скромный'],
  ['rō-bus-tus', 1, 'strong, of oak', 'stark, eichen', 'крепкий, дубовый'],
  ['per-fec-tus', 1, 'complete, perfect', 'vollendet', 'совершенный'],
  ['ab-sur-dus', 1, 'out of tune, absurd', 'misstönend, ungereimt', 'неблагозвучный, нелепый'],
  ['ve-nus-tus', 1, 'charming', 'anmutig', 'изящный'],
  ['se-cun-dus', 1, 'second, favourable', 'zweiter, günstig', 'второй, благоприятный'],
  ['ty-ran-nus', 1, 'tyrant', 'Tyrann', 'тиран'],
  ['fe-nes-tra', 1, 'window', 'Fenster', 'окно'],
  ['mi-nis-ter', 1, 'servant', 'Diener', 'слуга'],
  ['si-nis-ter', 1, 'left', 'links', 'левый'],
  ['a-lum-nus', 1, 'foster child, pupil', 'Zögling', 'воспитанник'],
  ['se-pul-crum', 1, 'tomb', 'Grab', 'гробница'],
  ['bap-tis-ma', 1, 'baptism', 'Taufe', 'крещение'],
  ['ex-cel-sīs', 1, '(in the) highest', '(in der) Höhe', '(в) вышних'],
  ['be-ne-dic-tus', 2, 'blessed', 'gesegnet', 'благословенный'],
  ['ex-em-plum', 1, 'example', 'Beispiel', 'пример'],
  ['mo-men-tum', 1, 'movement, moment', 'Bewegung, Augenblick', 'движение, миг'],
  ['mo-nu-men-tum', 2, 'reminder, monument', 'Denkmal', 'памятник'],
  ['ar-gu-men-tum', 2, 'proof, argument', 'Beweis, Argument', 'довод'],
  ['tes-ta-men-tum', 2, 'will, testament', 'Testament', 'завещание'],
  ['sa-crā-men-tum', 2, 'oath, sacrament', 'Eid, Sakrament', 'присяга, таинство'],
  ['fun-da-men-tum', 2, 'foundation', 'Fundament', 'основание'],
  ['in-strū-men-tum', 2, 'tool, equipment', 'Werkzeug', 'орудие'],
  ['a-gen-da', 1, 'things to be done', 'zu Tuendes', 'то, что надлежит сделать'],
  ['ad-den-da', 1, 'things to be added', 'Hinzuzufügendes', 'то, что следует добавить'],
  ['me-mo-ran-dum', 2, 'thing to be remembered', 'zu Merkendes', 'то, что следует помнить'],
  ['re-fe-ren-dum', 2, 'thing to be referred', 'Vorzulegendes', 'то, что следует передать (на решение)'],
  ['pro-pā-gan-da', 2, '(things) to be spread', 'zu Verbreitendes', 'то, что следует распространять'],
  ['cor-ri-gen-da', 2, 'things to be corrected', 'zu Berichtigendes', 'то, что следует исправить'],

  // ---- short penult: stress moves back ----
  ['fē-mi-na', 0, 'woman', 'Frau', 'женщина'],
  ['a-ni-ma', 0, 'soul, breath', 'Seele, Atem', 'душа, дыхание'],
  ['a-ni-mus', 0, 'mind, spirit', 'Geist, Mut', 'дух, ум'],
  ['po-pu-lus', 0, 'people', 'Volk', 'народ'],
  ['ta-bu-la', 0, 'board, tablet', 'Tafel', 'доска, табличка'],
  ['fā-bu-la', 0, 'story', 'Geschichte, Fabel', 'рассказ, басня'],
  ['in-su-la', 0, 'island', 'Insel', 'остров'],
  ['a-qui-la', 0, 'eagle', 'Adler', 'орёл'],
  ['lit-te-ra', 0, 'letter (of the alphabet)', 'Buchstabe', 'буква'],
  ['me-di-cus', 0, 'doctor', 'Arzt', 'врач'],
  ['pū-bli-cus', 0, 'public', 'öffentlich', 'общественный'],
  ['ca-tho-li-cus', 1, 'universal, catholic', 'allgemein, katholisch', 'вселенский, католический'],
  ['a-pos-to-li-cus', 2, 'apostolic', 'apostolisch', 'апостольский'],
  ['mū-si-ca', 0, 'music', 'Musik', 'музыка'],
  ['phy-si-ca', 0, 'physics, nature study', 'Physik, Naturlehre', 'физика'],
  ['lo-gi-ca', 0, 'logic', 'Logik', 'логика'],
  ['gram-ma-ti-ca', 1, 'grammar', 'Grammatik', 'грамматика'],
  ['di-gi-tus', 0, 'finger', 'Finger', 'палец'],
  ['o-cu-lus', 0, 'eye', 'Auge', 'глаз'],
  ['ti-tu-lus', 0, 'label, title', 'Aufschrift, Titel', 'надпись, титул'],
  ['sae-cu-lum', 0, 'age, century', 'Zeitalter, Jahrhundert', 'век, поколение'],
  ['vin-cu-lum', 0, 'chain, bond', 'Fessel, Band', 'оковы, узы'],
  ['pō-cu-lum', 0, 'cup', 'Becher', 'кубок'],
  ['cir-cu-lus', 0, 'circle', 'Kreis', 'круг'],
  ['nu-me-rus', 0, 'number', 'Zahl', 'число'],
  ['ter-mi-nus', 0, 'boundary, end', 'Grenze, Ende', 'граница, предел'],
  ['sti-mu-lus', 0, 'goad, spur', 'Stachel, Antrieb', 'стрекало, побуждение'],
  ['for-mu-la', 0, 'rule, formula', 'Regel, Formel', 'правило, формула'],
  ['cal-cu-lus', 0, 'pebble (for counting)', 'Rechenstein', 'камешек (для счёта)'],
  ['si-mi-lis', 0, 'similar', 'ähnlich', 'похожий'],
  ['fa-ci-lis', 0, 'easy', 'leicht', 'лёгкий'],
  ['dif-fi-ci-lis', 1, 'difficult', 'schwierig', 'трудный'],
  ['ū-ti-lis', 0, 'useful', 'nützlich', 'полезный'],
  ['nō-bi-lis', 0, 'noble, well-known', 'edel, bekannt', 'знатный, знаменитый'],
  ['mō-bi-lis', 0, 'movable', 'beweglich', 'подвижный'],
  ['hor-ri-bi-lis', 1, 'dreadful', 'schrecklich', 'ужасный'],
  ['ter-ri-bi-lis', 1, 'terrifying', 'furchtbar', 'страшный'],
  ['in-cog-ni-tus', 1, 'unknown', 'unbekannt', 'неизвестный'],
  ['in-co-la', 0, 'inhabitant', 'Einwohner', 'житель'],
  ['ca-me-ra', 0, 'vault, chamber', 'Gewölbe, Kammer', 'свод, комната'],
  ['an-ge-lus', 0, 'angel', 'Engel', 'ангел'],
  ['di-a-bo-lus', 1, 'devil', 'Teufel', 'дьявол'],
  ['spī-ri-tus', 0, 'breath, spirit', 'Hauch, Geist', 'дыхание, дух'],
  ['ex-er-ci-tus', 1, 'army', 'Heer', 'войско'],
  ['Her-cu-lēs', 0, 'Hercules', 'Herkules', 'Геркулес'],
  ['Rō-mu-lus', 0, 'Romulus', 'Romulus', 'Ромул'],
  ['Iup-pi-ter', 0, 'Jupiter', 'Jupiter', 'Юпитер'],
  ['Ā-fri-ca', 0, 'Africa', 'Afrika', 'Африка'],
  ['mī-rā-cu-lum', 1, 'wonder, miracle', 'Wunder', 'чудо'],
  ['spec-tā-cu-lum', 1, 'show, spectacle', 'Schauspiel', 'зрелище'],
  ['ō-rā-cu-lum', 1, 'oracle', 'Orakel', 'оракул'],
  ['pe-rī-cu-lum', 1, 'danger', 'Gefahr', 'опасность'],
  ['cur-ri-cu-lum', 1, 'race, racecourse', 'Lauf, Rennbahn', 'бег, ристалище'],

  // ---- short penult: vowel before a vowel ----
  ['Gal-li-a', 0, 'Gaul', 'Gallien', 'Галлия'],
  ['Grae-ci-a', 0, 'Greece', 'Griechenland', 'Греция'],
  ['A-si-a', 0, 'Asia', 'Asien', 'Азия'],
  ['I-ta-li-a', 1, 'Italy', 'Italien', 'Италия'],
  ['Ger-mā-ni-a', 1, 'Germania', 'Germanien', 'Германия'],
  ['Hi-spā-ni-a', 1, 'Spain', 'Spanien', 'Испания'],
  ['Bri-tan-ni-a', 1, 'Britain', 'Britannien', 'Британия'],
  ['Si-ci-li-a', 1, 'Sicily', 'Sizilien', 'Сицилия'],
  ['co-lō-ni-a', 1, 'colony; Cologne', 'Kolonie; Köln', 'колония; Кёльн'],
  ['Mār-ti-us', 0, 'March', 'März', 'март'],
  ['Iū-ni-us', 0, 'June', 'Juni', 'июнь'],
  ['Iū-li-us', 0, 'July; Julius', 'Juli; Julius', 'июль; Юлий'],
  ['Ver-gi-li-us', 1, 'Virgil', 'Vergil', 'Вергилий'],
  ['Ho-rā-ti-us', 1, 'Horace', 'Horaz', 'Гораций'],
  ['O-vi-di-us', 1, 'Ovid', 'Ovid', 'Овидий'],
  ['Ti-be-ri-us', 1, 'Tiberius', 'Tiberius', 'Тиберий'],
  ['Mer-cu-ri-us', 1, 'Mercury', 'Merkur', 'Меркурий'],
  ['Ca-pi-tō-li-um', 2, 'the Capitol', 'das Kapitol', 'Капитолий'],
  ['Ve-su-vi-us', 1, 'Vesuvius', 'Vesuv', 'Везувий'],
  ['pe-cū-ni-a', 1, 'money', 'Geld', 'деньги'],
  ['ec-clē-si-a', 1, 'assembly, church', 'Versammlung, Kirche', 'собрание, церковь'],
  ['glō-ri-a', 0, 'glory', 'Ruhm', 'слава'],
  ['grā-ti-a', 0, 'favour, grace, thanks', 'Gunst, Gnade, Dank', 'милость, благодать, благодарность'],
  ['me-mo-ri-a', 1, 'memory', 'Gedächtnis', 'память'],
  ['his-to-ri-a', 1, 'history, story', 'Geschichte', 'история'],
  ['phi-lo-so-phi-a', 2, 'philosophy', 'Philosophie', 'философия'],
  ['sa-pi-en-ti-a', 2, 'wisdom', 'Weisheit', 'мудрость'],
  ['sci-en-ti-a', 1, 'knowledge', 'Wissen', 'знание'],
  ['pa-ti-en-ti-a', 2, 'endurance, patience', 'Geduld', 'терпение'],
  ['fa-mi-li-a', 1, 'household', 'Hausgemeinschaft', 'домочадцы, семья'],
  ['vic-tō-ri-a', 1, 'victory', 'Sieg', 'победа'],
  ['cen-tu-ri-a', 1, 'a hundred, century', 'Hundertschaft', 'сотня, центурия'],
  ['dē-li-ci-ae', 1, 'delight, darling', 'Wonne, Liebling', 'наслаждение, любимец'],
  ['in-sig-ni-a', 1, 'badges, insignia', 'Abzeichen', 'знаки отличия'],
  ['fī-li-us', 0, 'son', 'Sohn', 'сын'],
  ['fī-li-a', 0, 'daughter', 'Tochter', 'дочь'],
  ['ra-di-us', 0, 'rod, ray', 'Stab, Strahl', 'луч, спица'],
  ['ge-ni-us', 0, 'guardian spirit', 'Schutzgeist', 'дух-хранитель'],
  ['me-di-um', 0, 'middle', 'Mitte', 'середина'],
  ['stu-di-um', 0, 'zeal, study', 'Eifer, Studium', 'усердие, занятие'],
  ['gau-di-um', 0, 'joy', 'Freude', 'радость'],
  ['o-di-um', 0, 'hatred', 'Hass', 'ненависть'],
  ['ā-tri-um', 0, 'hall, atrium', 'Halle, Atrium', 'атриум, зал'],
  ['va-cu-um', 0, 'empty space', 'leerer Raum', 'пустота'],
  ['nu-cle-us', 0, 'kernel, nut', 'Kern', 'ядро, орешек'],
  ['re-qui-em', 0, 'rest (acc.)', 'Ruhe (Akk.)', 'покой (вин. п.)'],
  ['cae-ru-le-us', 1, 'sky-blue', 'himmelblau', 'лазурный'],
  ['im-pe-ri-um', 1, 'command, empire', 'Befehl, Reich', 'власть, держава'],
  ['con-si-li-um', 1, 'plan, advice', 'Plan, Rat', 'замысел, совет'],
  ['au-xi-li-um', 1, 'help', 'Hilfe', 'помощь'],
  ['of-fi-ci-um', 1, 'duty', 'Pflicht', 'долг, обязанность'],
  ['prin-ci-pi-um', 1, 'beginning', 'Anfang', 'начало'],
  ['hos-pi-ti-um', 1, 'hospitality, lodging', 'Gastfreundschaft, Herberge', 'гостеприимство, приют'],
  ['mil-len-ni-um', 1, 'a thousand years (modern)', 'Jahrtausend (neulat.)', 'тысячелетие (новолат.)'],
  ['be-ne-fi-ci-um', 2, 'kindness, favour', 'Wohltat', 'благодеяние'],
  ['ae-di-fi-ci-um', 2, 'building', 'Gebäude', 'здание'],
  ['sa-cri-fi-ci-um', 2, 'sacrifice', 'Opfer', 'жертвоприношение'],
  ['e-van-ge-li-um', 2, 'good news, gospel', 'Evangelium', 'благая весть, Евангелие'],
  ['mo-nas-tē-ri-um', 2, 'monastery', 'Kloster', 'монастырь'],
];

export interface StressWord { syll: string[]; stress: number; gloss: L }

export const STRESS_WORDS: StressWord[] = ROWS.map(([w, stress, en, de, ru]) => ({
  syll: w.split('-'),
  stress,
  gloss: { en, de, ru },
}));

/** Stable key of a word (used for progress facts and answer ids). */
export const wordKey = (w: StressWord) => w.syll.join('');
